### ISSUE TITLE
Is it possible to add restraints to part of the sequence forming the binding pocket?

### ISSUE THREAD

**Issue by orli91** [zaixizhang/PocketGen#1]
Very interesting work!

Although your method is trained to predict the full pocket, do you expect it to work
properly (if not better) for partial binding site impainting (Fixing a parte of the residues)?
Are you planning to implement such possibility in the scripts or to fine-tune a model for such partial pocket sequence retrieval?

Thanks!

**Comment by zaixizhang** [comment]
Thanks for your interest in our work! Yes, we believe PocketGen can do partial binding site inpainting. There are no significant technical challenges in implementation. We will consider the possibility and the plan of fine-tuning such a model.

Bests,
