### ISSUE TITLE
Installation, Colab?, Arm compatibility

### ISSUE THREAD

**Issue by norsedrunkensailor** [zaixizhang/PocketGen#10]
Hellooo,

The .yaml is missing the openeye channel for the corresponding package, also the modeller version (10.4) is no longer supported by conda, and installation is difficult. Does this only work for CUDA 11?

Is there an ARM compatible .yaml? if possible... 

And lastly, if all else fails is a Google Colab notebook possible? 

Super excited to try out this method though! 

All the best, 
NDS

**Comment by zaixizhang** [comment]
Hi, Thanks for your interest in our work! In my server, I developed the model based on cuda 11, so I am not sure the package versions for other cuda.
