### ISSUE TITLE
Question about the validation/test set 

### ISSUE THREAD

**Issue by empyriumz** [zaixizhang/PocketGen#2]
Hi there,

Great work on PocketGen! I've been reviewing your paper and code, and I have a question about the data splitting and validation process for the CrossDocked dataset.

I downloaded the `crossdocked_split.pt` file from Zenodo and noticed something unexpected:

```python
a = torch.load('crossdocked_split.pt')
(set(a['val']) & set(a['test'])) == set(a['test'])
```

This returns True, indicating that the validation and test sets are identical. Is this intentional?

Could you please clarify if this is the intended data split, and if so, the reasoning behind it?

Thanks for any clarification you can provide!

**Comment by empyriumz** [comment]
BTW, the validation and the test set is identical for `bindingmoad_split.pt` as well.

**Comment by zaixizhang** [comment]
Hi,

Thanks for your interest in our work! The dataset split follows previous works such as Pocket2Mol (https://github.com/pengxingang/Pocket2Mol/tree/main), ResGen (https://github.com/HaotianZhangAI4Science/ResGen/tree/main), and SurfGen (https://github.com/HaotianZhangAI4Science/SurfGen), where the val and test set are set the same. For example, in https://github.com/pengxingang/Pocket2Mol/blob/836a0c4ce487297ad24bc54ac2ebd163de13242c/train.py#L73 train_set, val_set = subsets['train'], subsets['test']

**Comment by zaixizhang** [comment]
We guess the previous works take this setting for the simplicity and stability performance of model training. Thanks for your feedback!

**Comment by empyriumz** [comment]
@zaixizhang Thanks for explaining! I'm a bit concerned though - using the same data for validation and testing can lead to overly optimistic results. It's generally best practice to keep the test set separate to get a fair comparison against other models. Do you have any results from a truly independent test set? That would give us a clearer picture of PocketGen's actual capabilities.

**Comment by zaixizhang** [comment]
Hi,
Yes, we did case studies on independent data (therapeutic ligands from recent papers). You could take a look at Figure 3 of our preprint (https://www.biorxiv.org/content/10.1101/2024.02.25.581968v2.full.pdf+html). As for all the experiments, the baseline methods and PocketGen are trained with the same data split for a fair comparison. Thanks!

**Comment by empyriumz** [comment]
I see, I will take a closer look at the paper and the results. Thanks again for the clarification and I will close the issue now.
