### ISSUE TITLE
Unpacking Error Encountered While Running the Model

### ISSUE THREAD

**Issue by aaaaaaaaa21-code** [zaixizhang/PocketGen#3]
Hello, I encountered some issues while trying to run your model with the use case '2p16'. 
Here is the detailed error message:

Traceback (most recent call last):
  File "generate_new.py", line 305, in <module>
    aar, rmsd, attend_logits = model.generate(batch, dir_name)
  File "/home/dell/download/pocketgen/models/PD.py", line 354, in generate
    res_H, res_X, pred_ligand, ligand_feat, pred_res_type, attend_logits = self.encoder(res_H, res_X, res_S, res_batch, pred_ligand, ligand_feat, batch['ligand_mask'], batch['edit_residue_num'], residue_mask)
ValueError: not enough values to unpack (expected 6, got 5)

It seems that the return values from the function call are not as expected. Can you provide guidance on how to resolve this issue?
Thank you for your assistance!

**Comment by zaixizhang** [comment]
Thanks for your feedback! It seems to be an error caused by the inconsistency of different versions of PocketGen. We have updated the code and now it should work well for the generation. Thanks!

**Comment by aaaaaaaaa21-code** [comment]
> Thanks for your feedback! It seems to be an error caused by the inconsistency of different versions of PocketGen. We have updated the code and now it should work well for the generation. Thanks!

Thanks for your help, I successfully run the code!

**Comment by zaixizhang** [comment]
Great! Thanks!
