### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by OrangeCat7777777** [zaixizhang/PocketGen#8]
When trying to run train pipeline with the following config
```
path: ./data/crossdocked_pocket10
split: ./data/crossdocked_split.pt
```
where crossdocked data is downloaded from the provided Zenodo link, I encounterd the following error:
```
File "./models/PD.py", line 306, in forward
    res_H, res_X, ligand_pos, ligand_feat, pred_res_type = self.encoder(res_H, res_X, res_S, res_batch, pred_ligand, ligand_feat, ligand_mask, edit_residue_num, residue_mask) 
ValueError: too many values to unpack (expected 5)
```
What to do?

**Comment by zaixizhang** [comment]
Hi, thanks for your question. You could try our updated code. The error is because we may want to save the attention weights during inference for case study.

**Comment by xxrelax** [comment]
I'm using your main branch code, but I still have this problem

**Comment by zeroDtree** [comment]
I ran into this problem too, using code from the main branch.
